const { generateHTML, escapeHtml, generatePackageCards, writeHTMLFile } = require('../../lib/formatters/html-generator')
const fs = require('fs')

describe('HTML Generator', () => {
  describe('generateHTML', () => {
    test('generates valid HTML5 structure', () => {
      const scanResults = {
        packages: [
          { name: 'chalk', version: '4.1.2', license: 'MIT' }
        ]
      }

      const html = generateHTML(scanResults, 'MyApp')

      expect(html).toContain('<!DOCTYPE html>')
      expect(html).toContain('<html lang="en">')
      expect(html).toContain('<meta charset="UTF-8">')
      expect(html).toContain('<title>Open Source Licenses - MyApp</title>')
      expect(html).toContain('chalk v4.1.2')
      expect(html).toContain('License: MIT')
      expect(html).toContain('</html>')
    })

    test('includes mobile viewport meta tag', () => {
      const scanResults = { packages: [] }
      const html = generateHTML(scanResults, 'TestApp')

      expect(html).toContain('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
    })

    test('includes project name in title', () => {
      const scanResults = { packages: [] }
      const html = generateHTML(scanResults, 'CoolApp')

      expect(html).toContain('<title>Open Source Licenses - CoolApp</title>')
    })

    test('escapes project name in title', () => {
      const scanResults = { packages: [] }
      const html = generateHTML(scanResults, '<Script>Test</Script>')

      expect(html).toContain('<title>Open Source Licenses - &lt;Script&gt;Test&lt;/Script&gt;</title>')
      expect(html).not.toContain('<Script>')
    })

    test('includes inline CSS', () => {
      const scanResults = { packages: [] }
      const html = generateHTML(scanResults, 'MyApp')

      expect(html).toContain('<style>')
      expect(html).toContain('</style>')
      expect(html).toContain('font-family:')
      expect(html).toContain('max-width: 800px')
    })

    test('includes responsive CSS with media queries', () => {
      const scanResults = { packages: [] }
      const html = generateHTML(scanResults, 'MyApp')

      expect(html).toContain('@media (max-width: 768px)')
      expect(html).toContain('-apple-system')
      expect(html).toContain('BlinkMacSystemFont')
      expect(html).toContain('min-height: 44px') // Touch target
    })

    test('includes dark mode support', () => {
      const scanResults = { packages: [] }
      const html = generateHTML(scanResults, 'MyApp')

      expect(html).toContain('@media (prefers-color-scheme: dark)')
    })

    test('includes JavaScript for license text toggle', () => {
      const scanResults = { packages: [] }
      const html = generateHTML(scanResults, 'MyApp')

      expect(html).toContain('<script>')
      expect(html).toContain('querySelectorAll')
      expect(html).toContain('.show-license')
      expect(html).toContain('addEventListener')
    })

    test('includes LicenseGuard footer with link', () => {
      const scanResults = { packages: [] }
      const html = generateHTML(scanResults, 'MyApp')

      expect(html).toContain('Generated by')
      expect(html).toContain('LicenseGuard')
      expect(html).toContain('https://www.npmjs.com/package/licenseguard-cli')
    })

    test('handles empty packages array', () => {
      const scanResults = { packages: [] }
      const html = generateHTML(scanResults, 'MyApp')

      expect(html).toContain('<!DOCTYPE html>')
      expect(html).toContain('No packages found')
    })
  })

  describe('escapeHtml', () => {
    test('escapes ampersands', () => {
      const text = 'A & B'
      const escaped = escapeHtml(text)

      expect(escaped).toBe('A &amp; B')
    })

    test('escapes less than signs', () => {
      const text = '<script>'
      const escaped = escapeHtml(text)

      expect(escaped).toBe('&lt;script&gt;')
      expect(escaped).not.toContain('<script>')
    })

    test('escapes greater than signs', () => {
      const text = '</script>'
      const escaped = escapeHtml(text)

      expect(escaped).toBe('&lt;/script&gt;')
    })

    test('escapes double quotes', () => {
      const text = 'He said "hello"'
      const escaped = escapeHtml(text)

      expect(escaped).toBe('He said &quot;hello&quot;')
    })

    test('escapes single quotes', () => {
      const text = 'It\'s working'
      const escaped = escapeHtml(text)

      expect(escaped).toBe('It&#39;s working')
    })

    test('escapes all special characters together', () => {
      const text = '<script>alert("XSS")</script> & \'test\''
      const escaped = escapeHtml(text)

      expect(escaped).toBe('&lt;script&gt;alert(&quot;XSS&quot;)&lt;/script&gt; &amp; &#39;test&#39;')
      expect(escaped).not.toContain('<script>')
      expect(escaped).not.toContain('"')
    })

    test('handles empty string', () => {
      expect(escapeHtml('')).toBe('')
    })

    test('handles null', () => {
      expect(escapeHtml(null)).toBe('')
    })

    test('handles undefined', () => {
      expect(escapeHtml(undefined)).toBe('')
    })

    test('converts numbers to strings', () => {
      expect(escapeHtml(123)).toBe('123')
    })
  })

  describe('generatePackageCards', () => {
    test('sorts packages alphabetically', () => {
      const packages = [
        { name: 'zebra', version: '1.0.0', license: 'MIT' },
        { name: 'alpha', version: '1.0.0', license: 'MIT' },
        { name: 'beta', version: '1.0.0', license: 'MIT' }
      ]

      const html = generatePackageCards(packages)

      const alphaIndex = html.indexOf('alpha')
      const betaIndex = html.indexOf('beta')
      const zebraIndex = html.indexOf('zebra')

      expect(alphaIndex).toBeLessThan(betaIndex)
      expect(betaIndex).toBeLessThan(zebraIndex)
    })

    test('includes package name, version, and license', () => {
      const packages = [
        { name: 'chalk', version: '4.1.2', license: 'MIT' }
      ]

      const html = generatePackageCards(packages)

      expect(html).toContain('chalk v4.1.2')
      expect(html).toContain('License: MIT')
      expect(html).toContain('class="package-name"')
      expect(html).toContain('class="license"')
    })

    test('includes license text when available', () => {
      const packages = [{
        name: 'chalk',
        version: '4.1.2',
        license: 'MIT',
        licenseText: 'MIT License\n\nPermission is hereby granted...'
      }]

      const html = generatePackageCards(packages)

      expect(html).toContain('Show license text')
      expect(html).toContain('Permission is hereby granted')
      expect(html).toContain('class="license-text"')
      expect(html).toContain('class="show-license"')
    })

    test('handles missing license text gracefully', () => {
      const packages = [{
        name: 'chalk',
        version: '4.1.2',
        license: 'MIT'
        // No licenseText field
      }]

      const html = generatePackageCards(packages)

      expect(html).not.toContain('Show license text')
      expect(html).toContain('chalk v4.1.2')
      expect(html).toContain('License: MIT')
    })

    test('escapes package names with special characters', () => {
      const packages = [{
        name: '@org/lib<test>',
        version: '1.0.0',
        license: 'MIT'
      }]

      const html = generatePackageCards(packages)

      expect(html).toContain('&lt;test&gt;')
      expect(html).not.toContain('<test>')
    })

    test('escapes license text with special characters', () => {
      const packages = [{
        name: 'test',
        version: '1.0.0',
        license: 'MIT',
        licenseText: '<script>alert("XSS")</script>'
      }]

      const html = generatePackageCards(packages)

      expect(html).toContain('&lt;script&gt;')
      expect(html).not.toContain('<script>alert')
    })

    test('handles empty packages array', () => {
      const html = generatePackageCards([])

      expect(html).toContain('No packages found')
    })

    test('handles null packages', () => {
      const html = generatePackageCards(null)

      expect(html).toContain('No packages found')
    })

    test('handles undefined packages', () => {
      const html = generatePackageCards(undefined)

      expect(html).toContain('No packages found')
    })

    test('generates card with proper CSS classes', () => {
      const packages = [{
        name: 'test',
        version: '1.0.0',
        license: 'MIT'
      }]

      const html = generatePackageCards(packages)

      expect(html).toContain('class="package"')
      expect(html).toContain('class="package-name"')
      expect(html).toContain('class="license"')
    })
  })

  describe('writeHTMLFile', () => {
    let consoleLogSpy
    let consoleErrorSpy
    let processExitSpy
    let writeFileSyncSpy

    beforeEach(() => {
      consoleLogSpy = jest.spyOn(console, 'log').mockImplementation()
      consoleErrorSpy = jest.spyOn(console, 'error').mockImplementation()
      processExitSpy = jest.spyOn(process, 'exit').mockImplementation()
      writeFileSyncSpy = jest.spyOn(fs, 'writeFileSync').mockImplementation()
    })

    afterEach(() => {
      consoleLogSpy.mockRestore()
      consoleErrorSpy.mockRestore()
      processExitSpy.mockRestore()
      writeFileSyncSpy.mockRestore()
    })

    test('writes HTML file successfully', () => {
      const html = '<html></html>'
      const outputPath = './CREDITS.html'

      writeHTMLFile(html, outputPath)

      expect(writeFileSyncSpy).toHaveBeenCalledWith(outputPath, html, 'utf8')
      expect(consoleLogSpy).toHaveBeenCalledWith(
        expect.stringContaining('✓ Attribution page saved to: ./CREDITS.html')
      )
    })

    test('handles permission denied error (EACCES)', () => {
      writeFileSyncSpy.mockImplementation(() => {
        const error = new Error('Permission denied')
        error.code = 'EACCES'
        throw error
      })

      writeHTMLFile('<html></html>', './CREDITS.html')

      expect(consoleErrorSpy).toHaveBeenCalledWith(
        expect.stringContaining('✗ Error: Could not write CREDITS.html (permission denied)')
      )
      expect(consoleLogSpy).toHaveBeenCalledWith(
        expect.stringContaining('Try running with elevated permissions')
      )
      expect(processExitSpy).toHaveBeenCalledWith(1)
    })

    test('handles disk full error (ENOSPC)', () => {
      writeFileSyncSpy.mockImplementation(() => {
        const error = new Error('Disk full')
        error.code = 'ENOSPC'
        throw error
      })

      writeHTMLFile('<html></html>', './CREDITS.html')

      expect(consoleErrorSpy).toHaveBeenCalledWith(
        expect.stringContaining('✗ Error: Could not write CREDITS.html (disk full)')
      )
      expect(processExitSpy).toHaveBeenCalledWith(1)
    })

    test('handles generic write error', () => {
      writeFileSyncSpy.mockImplementation(() => {
        throw new Error('Unknown error')
      })

      writeHTMLFile('<html></html>', './CREDITS.html')

      expect(consoleErrorSpy).toHaveBeenCalledWith(
        expect.stringContaining('✗ Error: Could not write CREDITS.html (Unknown error)')
      )
      expect(processExitSpy).toHaveBeenCalledWith(1)
    })
  })

  describe('Integration - Full HTML Generation', () => {
    test('generates complete HTML with multiple packages', () => {
      const scanResults = {
        packages: [
          {
            name: 'axios',
            version: '1.0.0',
            license: 'MIT',
            licenseText: 'MIT License\n\nCopyright (c) 2014-present Matt Zabriskie'
          },
          {
            name: 'lodash',
            version: '4.17.21',
            license: 'MIT'
          },
          {
            name: 'chalk',
            version: '4.1.2',
            license: 'MIT',
            licenseText: 'MIT License\n\nCopyright (c) Sindre Sorhus'
          }
        ]
      }

      const html = generateHTML(scanResults, 'TestApp')

      // HTML structure
      expect(html).toContain('<!DOCTYPE html>')
      expect(html).toContain('<html lang="en">')
      expect(html).toContain('<title>Open Source Licenses - TestApp</title>')

      // All packages present
      expect(html).toContain('axios v1.0.0')
      expect(html).toContain('lodash v4.17.21')
      expect(html).toContain('chalk v4.1.2')

      // Alphabetical order (axios, chalk, lodash)
      const axiosIndex = html.indexOf('axios')
      const chalkIndex = html.indexOf('chalk')
      const lodashIndex = html.indexOf('lodash')
      expect(axiosIndex).toBeLessThan(chalkIndex)
      expect(chalkIndex).toBeLessThan(lodashIndex)

      // License texts included where available
      expect(html).toContain('Matt Zabriskie')
      expect(html).toContain('Sindre Sorhus')

      // lodash has no license text
      const lodashCardStart = html.indexOf('lodash v4.17.21')
      const lodashCardEnd = html.indexOf('</div>', lodashCardStart + 200)
      const lodashCard = html.substring(lodashCardStart, lodashCardEnd)
      expect(lodashCard).not.toContain('Show license text')
    })

    test('HTML is valid and complete', () => {
      const scanResults = {
        packages: [{ name: 'test', version: '1.0.0', license: 'MIT' }]
      }

      const html = generateHTML(scanResults, 'App')

      // Opening and closing tags balanced
      expect((html.match(/<html/g) || []).length).toBe((html.match(/<\/html>/g) || []).length)
      expect((html.match(/<head/g) || []).length).toBe((html.match(/<\/head>/g) || []).length)
      expect((html.match(/<body/g) || []).length).toBe((html.match(/<\/body>/g) || []).length)
      expect((html.match(/<style/g) || []).length).toBe((html.match(/<\/style>/g) || []).length)
      expect((html.match(/<script/g) || []).length).toBe((html.match(/<\/script>/g) || []).length)
    })
  })
})
